### ISSUE TITLE
Why are there private variable/method access level for presenters?

### ISSUE THREAD

**Issue by PayteR** [remp2020/crm-salesfunnel-module#3]
Hi, 
i want to extend for example this presenter https://github.com/remp2020/crm-salesfunnel-module/blob/master/src/presenters/SalesFunnelFrontendPresenter.php but and override just 2 methods, but it's not possible, because of private access level for variables and methods. Why aren't they as protected?

**Comment by rootpd** [comment]
Can you be more specific with your use case, what you ant to achieve and what you're trying to override?

The main reason why they're not protected but private is to make sure, that any of our changes in presenter won't create breaking change for any other implementation.

**Comment by PayteR** [comment]
When i want to extend just renderShow() and renderSubmit() methods from https://github.com/remp2020/crm-salesfunnel-module/blob/master/src/presenters/SalesFunnelFrontendPresenter.php it's not possible due to the limitation, so i need to copy the whole file in my Module

**Comment by rootpd** [comment]
Those are two fundamental methods of the Sales Funnel. Changing them is really not recommended and having your own presenter which calls `PaymentProcessor` at the end of all the handling is a better approach.

Still, you haven't shared the use case you're trying to achieve by overriding the methods - maybe there's a way how to achieve what you need without overriding it.

**Comment by PayteR** [comment]
My use case is to add new fields with user invoice detail info to the sales funnel presenter

**Comment by rootpd** [comment]
You can submit the fields under `payment_metadata` form field, like this:

```
<input type="text" name="payment_metadata[invoice_first_name]" />
```

When you submit the form, all the metadata will be stored in `payment_meta` table and linked to the payment it created. Once the payment is submitted (or sooner during the process), you can attach your module to some event (like `PaymentStatusChangeEvent`), load the metadata from `PaymentMetaRepository` (the `key` parameter would be `invoice_first_name`) and do whatever you'd need to with the invoice information you collected.

**Comment by PayteR** [comment]
Thank you
